### PR TITLE
Add ability to pass multiple params in redirect uri

### PR DESCRIPTION
**Pull request by StephaneRob**

### CODE REVIEW

**Comment by StephaneRob** [comment]
@danschultzer, any thoughts about this PR?

**Comment by danschultzer** [comment]
@StephaneRob yeah, got a few, and sorry for no reply, just haven't had the time to go over it properly. I'll get back to this ASAP. Appreciate your contribution and patience!

**Comment by danschultzer** [comment]
I've refactored it. It's been a while since I properly worked with this repo so it takes me a while to get back into it. The PR looks good, but I wonder why can't this be part of redirect uri params? This seems to be the same as if you just pass in `https://example.com/path?whever=test` as the redirect_uri? What's the use case?

**Comment by danschultzer** [comment]
The client would still provide the values right? So my thinking is that wouldn't this be the same as if the client sends the end-user with `redirect_uri=https://example.com/path?whever=test` param? The end user would be redirected to `https://example.com/path?state=STATE&whever=test` then so the client receives the `whatever` param.

As I said, haven't been working with this repo in a while, so I'm trying to think through this change and how it currently works.

**Comment by StephaneRob** [comment]
I see what you mean. In my use case, the client will build the authorize url
ex
```
https://myapp.com/authorize?client_id=xxx&redirect_uri=https://example.com&response_type=code&scope=public
```

My app will append a params (that the client is not aware of) but useful for my app and the authorization flow. 
the params will be part of the authorize forms.

```
https://myapp.com/authorize?client_id=xxx&redirect_uri=https://example.com&response_type=code&scope=public&whatever=test
```

This params may be useful for the client and want it the callback.

**Comment by danschultzer** [comment]
Oh, I think I understand now.

So the need is that these are params that you want access to in your backend as separate of the ExOAuth2Provider logic? And they only get set by the backend after the end user visits the authorize endpoint, so it can be used in the forms subsequently?

If that's the case, couldn't you just update the `redirect_uri` after you have set or processed the params and send that to the `ExOauth2Provider.Authorization.authorize/3` and `ExOauth2Provider.Authorization.deny/3` methods?

You could even utilize the `ExOauth2Provider.RedirectURI` module for that, e.g.:

```elixir
extras = %{a: a_value, b: b_value}
# Or if they already are part of the params:
# extras = Map.take(params, ~w(a b))
params = Map.update!(params, "redirect_uri", &ExOauth2Provider.RedirectURI(&1, extras))

ExOauth2Provider.Authorization.authorize(resource_owner, params, otp_app: :my_app) do
# ...
```

I think it's also how it's intended to work with the OAuth 2.0 specs, but I'll have to read up on that again 😄

Let me know if I understand your situation correctly, and if the above is a solution that works for you! It's not that I want to hold up this PR (especially since it's been open for so long, ugh!), but I think there may already be support for what you need, though it may not be obvious at first read.

**Comment by StephaneRob** [comment]
Yes it's exactly what i need. My first idea was actually to override the `redirect_uri` but was not really happy to modify a params I'm not completely responsible for and thought that it will be more elegant to process this params like the `state` one.

I understand you point of view, and will give it a try 👌 
I guess by `&ExOauth2Provider.RedirectURI(&1, extras)` you mean `&ExOauth2Provider.RedirectURI.uri_with_query(&1, extras)`

Btw. Thanks, for your lib is really great!

**Comment by danschultzer** [comment]
> I guess by `&ExOauth2Provider.RedirectURI(&1, extras)` you mean `&ExOauth2Provider.RedirectURI.uri_with_query(&1, extras)`

Yup! I haven't tested the above, but hopefully it's all that's needed.


> My first idea was actually to override the `redirect_uri` but was not really happy to modify a params I'm not completely responsible for and thought that it will be more elegant to process this params like the `state` one.

Yeah, I see that. I feel that it also makes the logic less explicit though. And I just realized that this PR makes it possible to ignore `state` which I don't think is spec compliant. If `state` is set by the client, then the backend must to return it in the redirect_uri.

In any case, if the above works then I think this is the preferred way of dealing with this. It might also be a good idea to add to the docs as I'm sure there are other devs who need the same logic, and it isn't really obvious how.

**Comment by StephaneRob** [comment]
Yes! I will be happy to contribute on the docs or other features!

**Comment by StephaneRob** [comment]
@danschultzer works perfectly with `&ExOauth2Provider.RedirectURI.uri_with_query(&1, extras)` ! 

About
> If state is set by the client, then the backend must to return it in the redirect_uri.

You're absolutely right.

> state
>         REQUIRED if the "state" parameter was present in the client
>         authorization request.  The exact value received from the
>        client.

We can close this PR.

**Pull request closed without merging**
